// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user_server

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Score                int32    `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,7,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	Description          string   `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *User) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type LoginData struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Score                int32    `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,6,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	Description          string   `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginData) Reset()         { *m = LoginData{} }
func (m *LoginData) String() string { return proto.CompactTextString(m) }
func (*LoginData) ProtoMessage()    {}
func (*LoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *LoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginData.Unmarshal(m, b)
}
func (m *LoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginData.Marshal(b, m, deterministic)
}
func (m *LoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginData.Merge(m, src)
}
func (m *LoginData) XXX_Size() int {
	return xxx_messageInfo_LoginData.Size(m)
}
func (m *LoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginData.DiscardUnknown(m)
}

var xxx_messageInfo_LoginData proto.InternalMessageInfo

func (m *LoginData) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *LoginData) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *LoginData) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *LoginData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginData) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *LoginData) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *LoginData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type LoginResponse struct {
	Status               uint32     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 *LoginData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Msg                  string     `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	SessionID            string     `protobuf:"bytes,4,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *LoginResponse) GetData() *LoginData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *LoginResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LoginResponse) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

type UpdateInput struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	SesionID             string   `protobuf:"bytes,2,opt,name=sesionID,proto3" json:"sesionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInput) Reset()         { *m = UpdateInput{} }
func (m *UpdateInput) String() string { return proto.CompactTextString(m) }
func (*UpdateInput) ProtoMessage()    {}
func (*UpdateInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UpdateInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInput.Unmarshal(m, b)
}
func (m *UpdateInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInput.Marshal(b, m, deterministic)
}
func (m *UpdateInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInput.Merge(m, src)
}
func (m *UpdateInput) XXX_Size() int {
	return xxx_messageInfo_UpdateInput.Size(m)
}
func (m *UpdateInput) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInput.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInput proto.InternalMessageInfo

func (m *UpdateInput) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateInput) GetSesionID() string {
	if m != nil {
		return m.SesionID
	}
	return ""
}

type LogoutResponse struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	GoodbyeMsg           string   `protobuf:"bytes,2,opt,name=goodbyeMsg,proto3" json:"goodbyeMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *LogoutResponse) GetGoodbyeMsg() string {
	if m != nil {
		return m.GoodbyeMsg
	}
	return ""
}

type GetUserData struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Score                int32    `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,6,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	Description          string   `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserData) Reset()         { *m = GetUserData{} }
func (m *GetUserData) String() string { return proto.CompactTextString(m) }
func (*GetUserData) ProtoMessage()    {}
func (*GetUserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *GetUserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserData.Unmarshal(m, b)
}
func (m *GetUserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserData.Marshal(b, m, deterministic)
}
func (m *GetUserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserData.Merge(m, src)
}
func (m *GetUserData) XXX_Size() int {
	return xxx_messageInfo_GetUserData.Size(m)
}
func (m *GetUserData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserData.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserData proto.InternalMessageInfo

func (m *GetUserData) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *GetUserData) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *GetUserData) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *GetUserData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserData) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *GetUserData) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *GetUserData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type GetUserResponse struct {
	Status               uint32       `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 *GetUserData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Msg                  string       `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetUserResponse) GetData() *GetUserData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetUserResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SignUpData struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	Surname              string   `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Score                int32    `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,6,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	Description          string   `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpData) Reset()         { *m = SignUpData{} }
func (m *SignUpData) String() string { return proto.CompactTextString(m) }
func (*SignUpData) ProtoMessage()    {}
func (*SignUpData) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *SignUpData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpData.Unmarshal(m, b)
}
func (m *SignUpData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpData.Marshal(b, m, deterministic)
}
func (m *SignUpData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpData.Merge(m, src)
}
func (m *SignUpData) XXX_Size() int {
	return xxx_messageInfo_SignUpData.Size(m)
}
func (m *SignUpData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpData.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpData proto.InternalMessageInfo

func (m *SignUpData) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *SignUpData) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *SignUpData) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *SignUpData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpData) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *SignUpData) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *SignUpData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type SignupResponse struct {
	Status               uint32      `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 *SignUpData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Msg                  string      `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	SessionID            string      `protobuf:"bytes,4,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SignupResponse) Reset()         { *m = SignupResponse{} }
func (m *SignupResponse) String() string { return proto.CompactTextString(m) }
func (*SignupResponse) ProtoMessage()    {}
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *SignupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupResponse.Unmarshal(m, b)
}
func (m *SignupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupResponse.Marshal(b, m, deterministic)
}
func (m *SignupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupResponse.Merge(m, src)
}
func (m *SignupResponse) XXX_Size() int {
	return xxx_messageInfo_SignupResponse.Size(m)
}
func (m *SignupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignupResponse proto.InternalMessageInfo

func (m *SignupResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SignupResponse) GetData() *SignUpData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SignupResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SignupResponse) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

type SessionID struct {
	SesionID             string   `protobuf:"bytes,1,opt,name=sesionID,proto3" json:"sesionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionID) Reset()         { *m = SessionID{} }
func (m *SessionID) String() string { return proto.CompactTextString(m) }
func (*SessionID) ProtoMessage()    {}
func (*SessionID) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *SessionID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionID.Unmarshal(m, b)
}
func (m *SessionID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionID.Marshal(b, m, deterministic)
}
func (m *SessionID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionID.Merge(m, src)
}
func (m *SessionID) XXX_Size() int {
	return xxx_messageInfo_SessionID.Size(m)
}
func (m *SessionID) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionID.DiscardUnknown(m)
}

var xxx_messageInfo_SessionID proto.InternalMessageInfo

func (m *SessionID) GetSesionID() string {
	if m != nil {
		return m.SesionID
	}
	return ""
}

type CookieValue struct {
	CookieValue          string   `protobuf:"bytes,1,opt,name=cookieValue,proto3" json:"cookieValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CookieValue) Reset()         { *m = CookieValue{} }
func (m *CookieValue) String() string { return proto.CompactTextString(m) }
func (*CookieValue) ProtoMessage()    {}
func (*CookieValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *CookieValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CookieValue.Unmarshal(m, b)
}
func (m *CookieValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CookieValue.Marshal(b, m, deterministic)
}
func (m *CookieValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CookieValue.Merge(m, src)
}
func (m *CookieValue) XXX_Size() int {
	return xxx_messageInfo_CookieValue.Size(m)
}
func (m *CookieValue) XXX_DiscardUnknown() {
	xxx_messageInfo_CookieValue.DiscardUnknown(m)
}

var xxx_messageInfo_CookieValue proto.InternalMessageInfo

func (m *CookieValue) GetCookieValue() string {
	if m != nil {
		return m.CookieValue
	}
	return ""
}

type Author struct {
	Author               string   `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Author) Reset()         { *m = Author{} }
func (m *Author) String() string { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()    {}
func (*Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Author.Unmarshal(m, b)
}
func (m *Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Author.Marshal(b, m, deterministic)
}
func (m *Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Author.Merge(m, src)
}
func (m *Author) XXX_Size() int {
	return xxx_messageInfo_Author.Size(m)
}
func (m *Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Author proto.InternalMessageInfo

func (m *Author) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

type Nothing struct {
	Dummy                bool     `protobuf:"varint,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nothing) Reset()         { *m = Nothing{} }
func (m *Nothing) String() string { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()    {}
func (*Nothing) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{12}
}

func (m *Nothing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nothing.Unmarshal(m, b)
}
func (m *Nothing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nothing.Marshal(b, m, deterministic)
}
func (m *Nothing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nothing.Merge(m, src)
}
func (m *Nothing) XXX_Size() int {
	return xxx_messageInfo_Nothing.Size(m)
}
func (m *Nothing) XXX_DiscardUnknown() {
	xxx_messageInfo_Nothing.DiscardUnknown(m)
}

var xxx_messageInfo_Nothing proto.InternalMessageInfo

func (m *Nothing) GetDummy() bool {
	if m != nil {
		return m.Dummy
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "user_server.User")
	proto.RegisterType((*LoginData)(nil), "user_server.LoginData")
	proto.RegisterType((*LoginResponse)(nil), "user_server.LoginResponse")
	proto.RegisterType((*UpdateInput)(nil), "user_server.UpdateInput")
	proto.RegisterType((*LogoutResponse)(nil), "user_server.LogoutResponse")
	proto.RegisterType((*GetUserData)(nil), "user_server.GetUserData")
	proto.RegisterType((*GetUserResponse)(nil), "user_server.GetUserResponse")
	proto.RegisterType((*SignUpData)(nil), "user_server.SignUpData")
	proto.RegisterType((*SignupResponse)(nil), "user_server.SignupResponse")
	proto.RegisterType((*SessionID)(nil), "user_server.SessionID")
	proto.RegisterType((*CookieValue)(nil), "user_server.CookieValue")
	proto.RegisterType((*Author)(nil), "user_server.Author")
	proto.RegisterType((*Nothing)(nil), "user_server.Nothing")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 611 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0x5f, 0x6b, 0xd4, 0x40,
	0x10, 0x6f, 0xec, 0x5d, 0xae, 0x37, 0xb1, 0xb5, 0xae, 0xa5, 0x86, 0xb3, 0xe8, 0x11, 0x10, 0x8b,
	0xca, 0x09, 0xe7, 0x9b, 0xf8, 0x22, 0x16, 0xae, 0x85, 0x5a, 0x4a, 0xca, 0xf9, 0x2a, 0xdb, 0xcb,
	0x36, 0x5d, 0xcc, 0x65, 0xc3, 0xee, 0xe6, 0xe4, 0x9e, 0xc5, 0xef, 0xe1, 0xa7, 0x51, 0xfc, 0x12,
	0x7e, 0x16, 0xd9, 0x3f, 0xf9, 0xd7, 0x6b, 0x09, 0xf4, 0xa1, 0xe0, 0xdb, 0xfe, 0x66, 0x76, 0x26,
	0xf3, 0xfb, 0xcd, 0xec, 0x04, 0x20, 0x17, 0x84, 0x8f, 0x32, 0xce, 0x24, 0x43, 0x9e, 0x3a, 0x7f,
	0x11, 0x84, 0x2f, 0x08, 0x0f, 0xfe, 0x3a, 0xd0, 0x99, 0x0a, 0xc2, 0xd1, 0x0e, 0x74, 0x13, 0x16,
	0xd3, 0xd4, 0x77, 0x86, 0xce, 0x7e, 0x3f, 0x34, 0x00, 0xed, 0x41, 0xff, 0x82, 0x72, 0x21, 0x4f,
	0xf0, 0x9c, 0xf8, 0xf7, 0xb4, 0xa7, 0x32, 0xa0, 0x01, 0x6c, 0x24, 0xd8, 0x3a, 0xd7, 0xb5, 0xb3,
	0xc4, 0x2a, 0x1f, 0x99, 0x63, 0x9a, 0xf8, 0x1d, 0x93, 0x4f, 0x03, 0x15, 0x91, 0x61, 0x21, 0xbe,
	0x31, 0x1e, 0xf9, 0x5d, 0x13, 0x51, 0x60, 0x15, 0x21, 0x66, 0x8c, 0x13, 0xdf, 0x1d, 0x3a, 0xfb,
	0xdd, 0xd0, 0x00, 0x55, 0x01, 0x5e, 0x60, 0x89, 0xf9, 0x94, 0x27, 0x7e, 0xcf, 0x54, 0x50, 0x1a,
	0xd0, 0x10, 0xbc, 0x88, 0x88, 0x19, 0xa7, 0x99, 0xa4, 0x2c, 0xf5, 0x37, 0xb4, 0xbf, 0x6e, 0x0a,
	0x7e, 0x3b, 0xd0, 0x3f, 0x56, 0x5c, 0x0e, 0xb0, 0xc4, 0x77, 0xc4, 0xb2, 0x64, 0xd2, 0xbd, 0x91,
	0x89, 0xdb, 0xc2, 0xa4, 0xb7, 0xca, 0xe4, 0xbb, 0x03, 0x9b, 0x9a, 0x49, 0x48, 0x44, 0xc6, 0x52,
	0x41, 0xd0, 0x2e, 0xb8, 0x42, 0x62, 0x99, 0x0b, 0x4d, 0x67, 0x33, 0xb4, 0x08, 0xbd, 0x84, 0x4e,
	0x84, 0x25, 0xd6, 0x54, 0xbc, 0xf1, 0xee, 0xa8, 0xd6, 0xf0, 0x51, 0xa9, 0x45, 0xa8, 0xef, 0xa0,
	0x6d, 0x58, 0x9f, 0x8b, 0xd8, 0x12, 0x53, 0x47, 0x55, 0xa7, 0x20, 0x42, 0x50, 0x96, 0x1e, 0x1d,
	0x58, 0x5e, 0x95, 0x21, 0x38, 0x05, 0x6f, 0x9a, 0x45, 0x58, 0x92, 0xa3, 0x34, 0xcb, 0x25, 0x7a,
	0x0e, 0x1d, 0x95, 0x5d, 0x17, 0xe0, 0x8d, 0x1f, 0x36, 0x3e, 0xa5, 0xe6, 0x2a, 0xd4, 0x6e, 0xa5,
	0xa1, 0x20, 0x36, 0xa5, 0x11, 0xb8, 0xc4, 0xc1, 0x21, 0x6c, 0x1d, 0xb3, 0x98, 0xe5, 0xb2, 0x95,
	0xd7, 0x53, 0x80, 0x98, 0xb1, 0xe8, 0x7c, 0x49, 0x3e, 0x89, 0xd8, 0xe6, 0xa9, 0x59, 0x82, 0x3f,
	0x0e, 0x78, 0x13, 0x22, 0xd5, 0x77, 0xff, 0xfb, 0x6e, 0x53, 0x78, 0x60, 0xa9, 0xb4, 0xca, 0xf2,
	0xba, 0xd1, 0x6e, 0xbf, 0xd1, 0x83, 0x9a, 0x1c, 0x37, 0x35, 0x3c, 0xf8, 0xe5, 0x00, 0x9c, 0xd1,
	0x38, 0x9d, 0x66, 0xb7, 0x56, 0xcd, 0x87, 0x9e, 0xc8, 0x79, 0x5a, 0x89, 0x56, 0xc0, 0x3b, 0xd5,
	0xec, 0x87, 0x03, 0x5b, 0x8a, 0x48, 0x9e, 0xb5, 0x6a, 0xf6, 0xaa, 0xa1, 0xd9, 0xe3, 0x86, 0x66,
	0x95, 0x16, 0xb7, 0x7c, 0x23, 0x2f, 0xa0, 0x7f, 0x56, 0x80, 0xc6, 0xe8, 0x3b, 0x57, 0x46, 0xff,
	0x0d, 0x78, 0x1f, 0x19, 0xfb, 0x4a, 0xc9, 0x67, 0x9c, 0xe4, 0x44, 0x31, 0x9c, 0x55, 0xd0, 0xde,
	0xae, 0x9b, 0x82, 0x21, 0xb8, 0x1f, 0x72, 0x79, 0xc9, 0xb8, 0x22, 0x86, 0xf5, 0xc9, 0x5e, 0xb3,
	0x28, 0x78, 0x06, 0xbd, 0x13, 0x26, 0x2f, 0x69, 0x1a, 0x2b, 0x91, 0xa3, 0x7c, 0x3e, 0x5f, 0xea,
	0x1b, 0x1b, 0xa1, 0x01, 0xe3, 0x9f, 0xeb, 0x70, 0x5f, 0x8f, 0x04, 0x49, 0xe8, 0x82, 0xf0, 0x25,
	0x9a, 0xc0, 0xa6, 0x79, 0xd1, 0xa7, 0x9c, 0x5d, 0xd0, 0x84, 0xa0, 0xe6, 0x04, 0xd5, 0x5e, 0xfb,
	0x60, 0xb0, 0xba, 0x4a, 0x0a, 0xa5, 0x83, 0x35, 0x34, 0x81, 0xed, 0x09, 0x91, 0xa6, 0xbe, 0x22,
	0xd7, 0xa3, 0x46, 0x84, 0xf1, 0x0d, 0xf6, 0xae, 0x1b, 0xd1, 0x5a, 0xa2, 0x43, 0xd8, 0xb2, 0xc6,
	0x22, 0x4d, 0x73, 0x87, 0x95, 0xe2, 0xb6, 0x66, 0x7a, 0x6f, 0x97, 0xbf, 0xfe, 0xc5, 0xad, 0x6e,
	0xa7, 0x16, 0x42, 0xef, 0xc0, 0x35, 0xe3, 0x74, 0x5d, 0xe8, 0x93, 0x95, 0x99, 0xa9, 0xc6, 0xce,
	0xc4, 0x9a, 0xad, 0x76, 0x45, 0xce, 0x5a, 0xbf, 0x07, 0x3b, 0x0d, 0x8f, 0x6d, 0x5b, 0xb0, 0x76,
	0xee, 0xea, 0x1f, 0xf5, 0xdb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x13, 0xde, 0xc0, 0xb6,
	0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserDeliveryClient is the client API for UserDelivery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserDeliveryClient interface {
	UpdateProfile(ctx context.Context, in *UpdateInput, opts ...grpc.CallOption) (*LoginResponse, error)
	GetAuthorProfile(ctx context.Context, in *Author, opts ...grpc.CallOption) (*GetUserResponse, error)
	GetUserProfile(ctx context.Context, in *SessionID, opts ...grpc.CallOption) (*GetUserResponse, error)
	LoginUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*LoginResponse, error)
	Signup(ctx context.Context, in *User, opts ...grpc.CallOption) (*SignupResponse, error)
	Logout(ctx context.Context, in *CookieValue, opts ...grpc.CallOption) (*Nothing, error)
}

type userDeliveryClient struct {
	cc *grpc.ClientConn
}

func NewUserDeliveryClient(cc *grpc.ClientConn) UserDeliveryClient {
	return &userDeliveryClient{cc}
}

func (c *userDeliveryClient) UpdateProfile(ctx context.Context, in *UpdateInput, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/user_server.UserDelivery/UpdateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDeliveryClient) GetAuthorProfile(ctx context.Context, in *Author, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/user_server.UserDelivery/GetAuthorProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDeliveryClient) GetUserProfile(ctx context.Context, in *SessionID, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/user_server.UserDelivery/GetUserProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDeliveryClient) LoginUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/user_server.UserDelivery/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDeliveryClient) Signup(ctx context.Context, in *User, opts ...grpc.CallOption) (*SignupResponse, error) {
	out := new(SignupResponse)
	err := c.cc.Invoke(ctx, "/user_server.UserDelivery/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDeliveryClient) Logout(ctx context.Context, in *CookieValue, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/user_server.UserDelivery/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserDeliveryServer is the server API for UserDelivery service.
type UserDeliveryServer interface {
	UpdateProfile(context.Context, *UpdateInput) (*LoginResponse, error)
	GetAuthorProfile(context.Context, *Author) (*GetUserResponse, error)
	GetUserProfile(context.Context, *SessionID) (*GetUserResponse, error)
	LoginUser(context.Context, *User) (*LoginResponse, error)
	Signup(context.Context, *User) (*SignupResponse, error)
	Logout(context.Context, *CookieValue) (*Nothing, error)
}

// UnimplementedUserDeliveryServer can be embedded to have forward compatible implementations.
type UnimplementedUserDeliveryServer struct {
}

func (*UnimplementedUserDeliveryServer) UpdateProfile(ctx context.Context, req *UpdateInput) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (*UnimplementedUserDeliveryServer) GetAuthorProfile(ctx context.Context, req *Author) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthorProfile not implemented")
}
func (*UnimplementedUserDeliveryServer) GetUserProfile(ctx context.Context, req *SessionID) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserProfile not implemented")
}
func (*UnimplementedUserDeliveryServer) LoginUser(ctx context.Context, req *User) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (*UnimplementedUserDeliveryServer) Signup(ctx context.Context, req *User) (*SignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (*UnimplementedUserDeliveryServer) Logout(ctx context.Context, req *CookieValue) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}

func RegisterUserDeliveryServer(s *grpc.Server, srv UserDeliveryServer) {
	s.RegisterService(&_UserDelivery_serviceDesc, srv)
}

func _UserDelivery_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDeliveryServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_server.UserDelivery/UpdateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDeliveryServer).UpdateProfile(ctx, req.(*UpdateInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDelivery_GetAuthorProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Author)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDeliveryServer).GetAuthorProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_server.UserDelivery/GetAuthorProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDeliveryServer).GetAuthorProfile(ctx, req.(*Author))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDelivery_GetUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDeliveryServer).GetUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_server.UserDelivery/GetUserProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDeliveryServer).GetUserProfile(ctx, req.(*SessionID))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDelivery_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDeliveryServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_server.UserDelivery/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDeliveryServer).LoginUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDelivery_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDeliveryServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_server.UserDelivery/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDeliveryServer).Signup(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDelivery_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CookieValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDeliveryServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_server.UserDelivery/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDeliveryServer).Logout(ctx, req.(*CookieValue))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserDelivery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user_server.UserDelivery",
	HandlerType: (*UserDeliveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateProfile",
			Handler:    _UserDelivery_UpdateProfile_Handler,
		},
		{
			MethodName: "GetAuthorProfile",
			Handler:    _UserDelivery_GetAuthorProfile_Handler,
		},
		{
			MethodName: "GetUserProfile",
			Handler:    _UserDelivery_GetUserProfile_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _UserDelivery_LoginUser_Handler,
		},
		{
			MethodName: "Signup",
			Handler:    _UserDelivery_Signup_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _UserDelivery_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
