linters:
  disable-all: true
  enable:
    - staticcheck
    - deadcode
    - errcheck
    - gosimple
    - govet
    - structcheck
    - typecheck
    - unused
    - varcheck
    - goimports
    - revive
run:
  tests: false
  skip-dirs:
    - internal/data
