// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonAb3363fcDecodeGithubComGoParkMailRu20212SaberDevsInternalLikesModels(in *jlexer.Lexer, out *LikeData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Ltype = int(in.Int())
		case "sign":
			out.Sign = int(in.Int())
		case "id":
			out.Id = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAb3363fcEncodeGithubComGoParkMailRu20212SaberDevsInternalLikesModels(out *jwriter.Writer, in LikeData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Ltype))
	}
	{
		const prefix string = ",\"sign\":"
		out.RawString(prefix)
		out.Int(int(in.Sign))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.Int(int(in.Id))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LikeData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAb3363fcEncodeGithubComGoParkMailRu20212SaberDevsInternalLikesModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LikeData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAb3363fcEncodeGithubComGoParkMailRu20212SaberDevsInternalLikesModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LikeData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAb3363fcDecodeGithubComGoParkMailRu20212SaberDevsInternalLikesModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LikeData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAb3363fcDecodeGithubComGoParkMailRu20212SaberDevsInternalLikesModels(l, v)
}
func easyjsonAb3363fcDecodeGithubComGoParkMailRu20212SaberDevsInternalLikesModels1(in *jlexer.Lexer, out *GenericResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "status":
			out.Status = uint(in.Uint())
		case "data":
			out.Data = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAb3363fcEncodeGithubComGoParkMailRu20212SaberDevsInternalLikesModels1(out *jwriter.Writer, in GenericResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.Uint(uint(in.Status))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.String(string(in.Data))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GenericResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAb3363fcEncodeGithubComGoParkMailRu20212SaberDevsInternalLikesModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GenericResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAb3363fcEncodeGithubComGoParkMailRu20212SaberDevsInternalLikesModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GenericResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAb3363fcDecodeGithubComGoParkMailRu20212SaberDevsInternalLikesModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GenericResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAb3363fcDecodeGithubComGoParkMailRu20212SaberDevsInternalLikesModels1(l, v)
}
