// Code generated by MockGen. DO NOT EDIT.
// Source: key.go

// Package mock_models is a generated GoMock package.
package mock_models

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2021_2_SaberDevs/internal/keys/models"
	gomock "github.com/golang/mock/gomock"
)

// MockKeyRepository is a mock of KeyRepository interface.
type MockKeyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockKeyRepositoryMockRecorder
}

// MockKeyRepositoryMockRecorder is the mock recorder for MockKeyRepository.
type MockKeyRepositoryMockRecorder struct {
	mock *MockKeyRepository
}

// NewMockKeyRepository creates a new mock instance.
func NewMockKeyRepository(ctrl *gomock.Controller) *MockKeyRepository {
	mock := &MockKeyRepository{ctrl: ctrl}
	mock.recorder = &MockKeyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyRepository) EXPECT() *MockKeyRepositoryMockRecorder {
	return m.recorder
}

// GetSalt mocks base method.
func (m *MockKeyRepository) GetSalt(ctx context.Context, login string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSalt", ctx, login)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSalt indicates an expected call of GetSalt.
func (mr *MockKeyRepositoryMockRecorder) GetSalt(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSalt", reflect.TypeOf((*MockKeyRepository)(nil).GetSalt), ctx, login)
}

// StoreSalt mocks base method.
func (m *MockKeyRepository) StoreSalt(ctx context.Context, key models.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreSalt", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreSalt indicates an expected call of StoreSalt.
func (mr *MockKeyRepositoryMockRecorder) StoreSalt(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreSalt", reflect.TypeOf((*MockKeyRepository)(nil).StoreSalt), ctx, key)
}
